# vim: set ft=dockerfile:

# Best to compile and test as non-root
ARG nonroot_uid=3973


FROM python:3.9 AS py39

RUN echo "${PYTHON_VERSION}" > /tmp/py39-latest


FROM rockylinux:9 AS base

RUN dnf makecache \
 && dnf update -y \
 && dnf install -y --allowerasing \
        curl \
        dnf-plugins-core \
 && dnf config-manager --set-enabled crb \
 && dnf install -y \
        bzip2-devel \
        findutils \
        gcc \
        gcc-c++ \
        git \
        libffi-devel \
        make \
        openssl-devel \
        python-devel \
        python3-pip \
        wget \
        xz \
        zlib-devel \
        sqlite-devel \
        unixODBC-devel \
        nc \
 && dnf clean all

##------------------------------------------------------------------------------
FROM base AS builder-base


RUN mkdir /usr/local/openssl11 \
 && cd /usr/local/openssl11 \
 && ln -s /usr/lib64/openssl11 lib \
 && ln -s /usr/include/openssl11 include

RUN mkdir /src



##------------------------------------------------------------------------------
FROM builder-base AS builder-py39
ARG py_ver=39
ARG nonroot_uid
COPY --from=py39 /tmp/py${py_ver}-latest /tmp/

RUN mkdir /opt/py${py_ver} && chown -R ${nonroot_uid} /opt/py${py_ver} /src
USER ${nonroot_uid}
WORKDIR /tmp

RUN export PYTHON_VERSION="$(cat /tmp/py${py_ver}-latest)" \
 && curl --silent --show-error --fail --location \
        "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz" \
    | tar -xz

RUN export PYTHON_VERSION="$(cat /tmp/py${py_ver}-latest)" \
 && cd "/tmp/Python-${PYTHON_VERSION}" \
 && ./configure --prefix=/opt/py${py_ver}  --enable-optimizations \
 && make -j 4 altinstall

USER root
ENV PATH=/opt/py${py_ver}/bin:"${PATH}"
RUN pip3 install tox
USER ${nonroot_uid}

ENV HOME=/src
ENV PATH=/opt/py${py_ver}/bin:"${PATH}"
WORKDIR /src

ADD django_informixdb/ /src/django_informixdb/
ADD README.rst setup.* tox.ini /src/
RUN tox -e "$(tox --listenvs | grep py${py_ver} | tr '\n' ',')" --notest  # prep venvs



##------------------------------------------------------------------------------
FROM base AS csdk
ARG nonroot_uid

COPY --chown=${nonroot_uid} \
     --from=ibmcom/informix-developer-sandbox@sha256:678250715879a7cbdd2ea658ff7ecd7087dcaf0b8e39d47c936916edff62c5ec \
        /home/informix/odbc/ /opt/IBM/informix/

##------------------------------------------------------------------------------
FROM csdk AS multipy
ARG nonroot_uid


COPY --from=builder-py39 /opt/py39/ /opt/py39/
COPY --from=builder-py39 /src/.tox/ /src/.tox/
COPY --from=builder-py39 /src/.cache/ /src/.cache/


ADD wait-for-deps.sh /usr/local/bin
RUN chmod a+rx /usr/local/bin/wait-for-deps.sh

ADD --chown=${nonroot_uid} README.rst setup.* tox.ini /src/
ADD --chown=${nonroot_uid} django_informixdb/ /src/django_informixdb/
ADD --chown=${nonroot_uid} test/ /src/test/
RUN chown ${nonroot_uid} /src

ENV PATH=/opt/py39/bin:"${PATH}"
RUN pip3 --no-cache-dir install tox

USER ${nonroot_uid}
ENV HOME=/src
WORKDIR /src
